Finishing Challenge....Pipeline adding test Application...v1.

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -94,4 +94,23 @@ jobs:
         echo ".......[$VERSION_TAG]......."
         sed -i.bak "s|DOCKER_TAG|${VERSION_TAG}|g" ./manifest/replicaset.yaml && \
         kubectl apply -f ./manifest/replicaset.yaml
-#       
+# 
+  test:
+    needs: setup-build-publish-deploy
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Run Test Script
+        run: bash a.sh
+        id: test_script
+        
+      - name: Test Script App
+        run: |
+          response_code=$(echo "${{ steps.test_script.outputs.stdout }}" | jq -r '.code')
+
+          if [ "$response_code" -eq 200 ]; then
+            echo "Test passed. Status code: $response_code"
+          else
+            echo "Test failed. Status code: $response_code"
+            exit 1  # Fail the workflow if the test fails
+          fi
