Updating Pipeline adding test docker image.....

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -41,6 +41,14 @@ jobs:
         run: |
           echo LASTEST_TAG=$(echo ${{ steps.version_step.outputs.latest_tag  }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
           echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
+      - name: Check if Docker image exists
+        run: |
+          if docker manifest inspect ${{env.LASTEST_TAG}} &> /dev/null; then
+            echo "Image ${{env.LASTEST_TAG}} exists."
+          else
+            echo "Image ${{env.LASTEST_TAG}} does not exist."
+            exit 1  # Fail the workflow if the image doesn't exist
+          fi
       - name: Build and push
         id: docker_build
         uses: docker/build-push-action@v5
